image: "python:3.10"

before_script:
  - pip install flake8 pytest
  - pip install -e .
  - pip install -r docs/requirements.txt
  - mkdir tests/test_data/save_path

stages:
  - Static Analysis
  - Test
  - deploy

flake8:
  stage: Static Analysis
  script:
    - flake8 --max-line-length=88 --extend-ignore=E203 src/ 

pytest:
  stage: Test
  script:
  - pytest tests/

pages:
  stage: deploy
  script:
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
